name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: | 
        sudo apt update; \
        sudo apt install -y git coreutils ruby-dev build-essential; \
        sudo gem install bundler; \
        ls -lrt; \
        echo "change permissions /var/lib/gems"; \
        sudo chown runner:docker -R /var/lib/gems; \
        echo "run bundle"; \
        bundle; \
        echo "run init"
        ./tools/init;
